[package]
name = "extism-pdk"
version = "0.0.1-rc.5"
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/extism/rust-pdk"
description = "Extism Plug-in Development Kit (PDK) for Rust"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
extism-manifest = "0.0.1-rc.5"
extism-pdk-derive = {path = "./derive"}

[workspace]
members = [
  ".",
  "derive"
]
