[package]
name = "extism-pdk"
version = "0.0.1-rc.2"
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/extism/rust-pdk"
description = "Extism Plug-in Development Kit (PDK) for Rust"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
extism-manifest = "0.0.1-rc.2"
